name: facebook_clone
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # firebase
  cloud_firestore: ^5.4.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+3
  
  # birthday date picker
  flutter_holo_date_picker: ^2.0.0

  # for providing icons
  font_awesome_flutter: ^10.7.0

  # formatting dates and timeago
  jiffy: ^6.3.1

  # generating ids for users
  uuid: ^4.5.1

  # state management
  flutter_riverpod: ^2.3.7

  # show toast message
  fluttertoast: ^8.2.8

  # pick images
  image_picker: ^1.1.2

  # play videos
  video_player: ^2.9.1

  # for displaying the stories
  story_view: ^0.16.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/