// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxVhu0B6ZnSwsyO5EYAYGGEJn4Zc4yuUY',
    appId: '1:12134254773:web:e72082a729fa0eb35456fc',
    messagingSenderId: '12134254773',
    projectId: 'facebook-clone-fb58c',
    authDomain: 'facebook-clone-fb58c.firebaseapp.com',
    storageBucket: 'facebook-clone-fb58c.appspot.com',
    measurementId: 'G-KHMHV2E60X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ0xACrHBLyeGKsJMZQYZUNs00iHVYzkU',
    appId: '1:12134254773:android:662715a1cde1e6085456fc',
    messagingSenderId: '12134254773',
    projectId: 'facebook-clone-fb58c',
    storageBucket: 'facebook-clone-fb58c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SfdV5pdPpWo_DxBmUnrwL8az6TUuKNY',
    appId: '1:12134254773:ios:184a2442303f0df25456fc',
    messagingSenderId: '12134254773',
    projectId: 'facebook-clone-fb58c',
    storageBucket: 'facebook-clone-fb58c.appspot.com',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7SfdV5pdPpWo_DxBmUnrwL8az6TUuKNY',
    appId: '1:12134254773:ios:184a2442303f0df25456fc',
    messagingSenderId: '12134254773',
    projectId: 'facebook-clone-fb58c',
    storageBucket: 'facebook-clone-fb58c.appspot.com',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxVhu0B6ZnSwsyO5EYAYGGEJn4Zc4yuUY',
    appId: '1:12134254773:web:7eaaad46c4e234575456fc',
    messagingSenderId: '12134254773',
    projectId: 'facebook-clone-fb58c',
    authDomain: 'facebook-clone-fb58c.firebaseapp.com',
    storageBucket: 'facebook-clone-fb58c.appspot.com',
    measurementId: 'G-VMWH3Z1MR7',
  );
}
